//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkProd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm : System.ComponentModel.INotifyPropertyChanged 
    {
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            public void OnPropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string name = "")
            {
                PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(name));
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Farm()
        {
            this.FarmProd = new System.Collections.ObjectModel.ObservableCollection<FarmProd>();
        }
    
        
    			private int _id_farm;
    			public int id_farm 
    			{ 
    				get => _id_farm; 
    				set
    				{ 
    					if(_id_farm!=value)
    					{ 
    						_id_farm=value; 
    						OnPropertyChanged("id_farm"); 
    					}
    				}
    			}
        
    			private string _name_farm;
    			public string name_farm 
    			{ 
    				get => _name_farm; 
    				set
    				{ 
    					if(_name_farm!=value)
    					{ 
    						_name_farm=value; 
    						OnPropertyChanged("name_farm"); 
    					}
    				}
    			}
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual System.Collections.ObjectModel.ObservableCollection<FarmProd> FarmProd { get; set; }
    }
}
