//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkProd
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmProd
    {
        public int id_farmprod { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_farm { get; set; }
        public Nullable<int> amount_farmprod { get; set; }
    
        public virtual Farm Farm { get; set; }
        public virtual Product Product { get; set; }
    }
}
