//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkProd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTrade
    {
        public int id_productTrade { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_trade { get; set; }
        public Nullable<int> amount_productTrade { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Trade Trade { get; set; }
    }
}
