//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkProd
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeProduct : System.ComponentModel.INotifyPropertyChanged 
    {
     public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            public void OnPropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string name = "")
            {
                PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(name));
            }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeProduct()
        {
            this.Product = new System.Collections.ObjectModel.ObservableCollection<Product>();
        }
    
        
    			private int _id_type;
    			public int id_type 
    			{ 
    				get => _id_type; 
    				set
    				{ 
    					if(_id_type!=value)
    					{ 
    						_id_type=value; 
    						OnPropertyChanged("id_type"); 
    					}
    				}
    			}
        
    			private string _name_type;
    			public string name_type 
    			{ 
    				get => _name_type; 
    				set
    				{ 
    					if(_name_type!=value)
    					{ 
    						_name_type=value; 
    						OnPropertyChanged("name_type"); 
    					}
    				}
    			}
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual System.Collections.ObjectModel.ObservableCollection<Product> Product { get; set; }
    }
}
