//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkProd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Trade = new HashSet<Trade>();
        }
    
        public int id_worker { get; set; }
        public string surname_worker { get; set; }
        public string name_worker { get; set; }
        public string patronymic_worker { get; set; }
        public Nullable<int> id_type { get; set; }
        public string telephone_worker { get; set; }
        public string login_worker { get; set; }
        public string password_worker { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trade> Trade { get; set; }
        public virtual TypeWorker TypeWorker { get; set; }
    }
}
